version: 2.1

references:
  decrypt_secrets: &decrypt_secrets
    run:
      name: Decrypt secrets file
      command: |
        echo "${GIT_CRYPT_KEY}" | base64 -d > git-crypt.key
        git-crypt unlock git-crypt.key

  setup_python_env: &setup_python_env
    run:
      name: Set up python dependencies
      command: |
        apk add linux-headers
        apk add python3-dev
        python3 -m venv venv
        pip3 install -r requirements/base.txt

  build_docker_image: &build_docker_image
    run:
      name: Build laa-fee-calculator docker image
      command: |
        export BUILD_DATE=$(date -Is) >> $BASH_ENV
        source $BASH_ENV
        docker build \
          --build-arg DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} \
          --build-arg VERSION_NUMBER=${CIRCLE_BUILD_NUM} \
          --build-arg COMMIT_ID=${CIRCLE_SHA1} \
          --build-arg BUILD_DATE=${BUILD_DATE} \
          --build-arg BUILD_TAG=${CIRCLE_BRANCH} \
          -t app .

  push_docker_image: &push_docker_image
    run:
      name: Push laa-fee-calculator docker image
      command: |
        login="$(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)"
        ${login}

        component=app
        docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${component}-${CIRCLE_SHA1}"
        docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${component}-${CIRCLE_SHA1}"

        if [ "${CIRCLE_BRANCH}" == "master" ]; then
          docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${component}-latest"
          docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${component}-latest"
        fi

# ------------------
# EXECUTORS
# ------------------
executors:
  cloud-platform-executor:
    docker:
      - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
        environment:
          GITHUB_TEAM_NAME_SLUG: laa-get-paid
          APPLICATION_DEPLOY_NAME: laa-fee-calculator
          DJANGO_SECRET_KEY: real-secret-not-needed-here

# ------------------
# COMMANDS
# ------------------
commands:
  deploy-to:
    description: >
      Deploy laa-fee-calculator to the specified environment
    parameters:
      environment:
        description: destination environment
        type: string
    steps:
      - checkout
      - run:
          name: Kubectl authentication
          command: |
            setup-kube-auth
            kubectl config use-context << parameters.environment >>
      - *decrypt_secrets
      - run:
          name: deploying to << parameters.environment >>
          command: |
            docker_image_tag=${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:app-${CIRCLE_SHA1}
            kubectl set image -f kubernetes_deploy/live-1/<< parameters.environment >>/deployment.yaml app=${docker_image_tag} --local -o yaml \
            | kubectl apply -f -
            kubectl apply \
                -f kubernetes_deploy/live-1/<< parameters.environment >>/service.yaml \
                -f kubernetes_deploy/live-1/<< parameters.environment >>/ingress.yaml \
                -f kubernetes_deploy/live-1/<< parameters.environment >>/django-secret.yaml

            sentry_dsn_secret=kubernetes_deploy/live-1/<< parameters.environment >>/sentry-dsn.yaml
            [ -f "$sentry_dsn_secret" ] && kubectl apply -f $sentry_dsn_secret

            kubectl annotate deployments/laa-fee-calculator kubernetes.io/change-cause="$(date) - circleCI deploying: $docker_image_tag"
            kubectl rollout restart deployments/laa-fee-calculator

# ------------------
# JOBS
# ------------------
jobs:
  test:
    executor: cloud-platform-executor
    parallelism: 2
    steps:
      - checkout
      - *setup_python_env
      - run:
          name: Split and run tests
          command: |
            TESTDOTPATHS=$(circleci tests glob "fee_calculator/apps/calculator/tests/**/test_*.py" | sed -e 's|\.py||g' -e 's|/|.|g' | circleci tests split)
            python3 manage.py test $TESTDOTPATHS --verbosity=1 --noinput

  build:
    executor: cloud-platform-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *build_docker_image
      - *push_docker_image

  staging_deploy:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: staging

  production_deploy:
    executor: cloud-platform-executor
    steps:
      - deploy-to:
          environment: production

# ------------------
# WORKFLOWS
# ------------------
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - staging_deploy_approval:
          type: approval
          requires:
            - build
      - staging_deploy:
          requires:
            - staging_deploy_approval
      - production_deploy_approval:
          type: approval
          requires:
            - staging_deploy
          filters:
            branches:
                only:
                  - master
      - production_deploy:
          requires:
            - production_deploy_approval
