version: 2
jobs:
  build:
    docker:
      - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
        environment:
          GITHUB_TEAM_NAME_SLUG: claim-for-crown-court-defence
          APPLICATION_DEPLOY_NAME: laa-fee-calculator
          DJANGO_SECRET_KEY: laa-fee-calculator
          # APPLICATION_HOST_URL: laa-fee-calculator-dev.apps.cloud-platform-test-1.k8s.integration.dsd.io
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
            name: Build application Docker image
            command: |
              docker build --build-arg DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} -t app .
      - deploy:
            name: Push application Docker image
            command: |
              login="$(aws ecr get-login --region eu-west-1 --no-include-email)"
              ${login}

              docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
              docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"

              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:latest"
                docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:latest"
              fi

  staging_deploy:
    docker:
      - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
        environment:
          GITHUB_TEAM_NAME_SLUG: claim-for-crown-court-defence
          APPLICATION_DEPLOY_NAME: laa-fee-calculator
          HOSTNAME: laa-fee-calculator-staging.apps.cloud-platform-live-0.k8s.integration.dsd.io
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
            name: Kubectl deployment
            command: |
              setup-kube-auth
              kubectl config use-context staging
              kubectl set image -f kubernetes_deploy/deployment.yaml app=${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} --local -o yaml \
                | kubectl apply -f -
              sed -E 's/([[:space:]]+- host: ).+/\1${HOSTNAME}/' kubernetes_deploy/ingress.yaml | kubectl apply -f -
              kubectl apply  -f kubernetes_deploy/service.yaml

  production_deploy:
    docker:
      - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
        environment:
          GITHUB_TEAM_NAME_SLUG: claim-for-crown-court-defence
          APPLICATION_DEPLOY_NAME: laa-fee-calculator
          HOSTNAME: laa-fee-calculator.apps.cloud-platform-live-0.k8s.integration.dsd.io
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
            name: Kubectl deployment
            command: |
              setup-kube-auth
              kubectl config use-context production
              kubectl set image -f kubernetes_deploy/deployment.yaml app=${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} --local -o yaml \
                | kubectl apply -f -
              sed -E 's/([[:space:]]+- host: ).+/\1${HOSTNAME}/' kubernetes_deploy/ingress.yaml | kubectl apply -f -
              kubectl apply -f kubernetes_deploy/ingress.yaml -f kubernetes_deploy/service.yaml

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs: 
      - build
      - staging_deploy_approval:
          type: approval
          requires: 
            - build
      - staging_deploy:
          requires:
            - staging_deploy_approval
      - production_deploy_approval:
          type: approval
          requires: 
            - build
            - staging_deploy
      - production_deploy:
          requires:
            - production_deploy_approval
            - staging_deploy
