apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laa-fee-calculator
  namespace: laa-fee-calculator-staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - laa-fee-calculator-staging.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: laa-fee-calculator-staging.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: laa-fee-calculator
          servicePort: 8080
